package json_template

import (
	"bytes"
	"encoding/json"
	"errors"
	"log/slog"
	"text/template"

	webhook "github.com/CyberDruga/fanbox2discord/src/models/discord"
	"github.com/CyberDruga/fanbox2discord/src/models/fanbox"
)

func ApplyTemplate(message string, source fanbox.Post) (result webhook.WebhookMessage, err error) {

	if message == "" {
		panic("[message] should never be empty")
	}

	templ, err := template.New("Discord Webhook Message").Parse(message)
	if err != nil {
		err = errors.Join(errors.New("Couldn't initialize template"), err)
		slog.Error(err.Error())
		return
	}

	var buf bytes.Buffer

	if err = templ.Execute(&buf, source); err != nil {
		err = errors.Join(errors.New("Couldn't parse template"), err)
		slog.Error(err.Error())
		return
	}

	if err = json.Unmarshal(buf.Bytes(), &result); err != nil {
		err = errors.Join(errors.New("Couldn't parse the json generated by the template"), err)
		slog.Error(
			err.Error(),
			"buf", string(buf.String()),
		)
		return
	}

	return
}
