// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const getPost = `-- name: GetPost :one
select post_id, creator_id from posts where post_id = ?
`

func (q *Queries) GetPost(ctx context.Context, postID string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, postID)
	var i Post
	err := row.Scan(&i.PostID, &i.CreatorID)
	return i, err
}

const getSavedPosts = `-- name: GetSavedPosts :many
select post_id, creator_id from posts where creator_id = ?
`

func (q *Queries) GetSavedPosts(ctx context.Context, creatorID string) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getSavedPosts, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(&i.PostID, &i.CreatorID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveNewPost = `-- name: SaveNewPost :one
insert into posts (post_id, creator_id)
values (?, ?) returning post_id, creator_id
`

type SaveNewPostParams struct {
	PostID    string
	CreatorID string
}

func (q *Queries) SaveNewPost(ctx context.Context, arg SaveNewPostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, saveNewPost, arg.PostID, arg.CreatorID)
	var i Post
	err := row.Scan(&i.PostID, &i.CreatorID)
	return i, err
}
